# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-10 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generallogger',
            name='usr_time',
        ),
    ]
